### ISSUE TITLE
Sorting items in plug-in chips drop down menu

### ISSUE THREAD

**Issue by hieuv** [CensoredUsername/Nier-Automata-editor#3]
The drop down menu to choose plug-in chips is in no order, making browsing for chips very difficult. I think it would be nice to have it sorted in alphabetical order.

I attempted to fix it by changing [definition of AVAILABLE_CHIPS in chips.py](https://github.com/CensoredUsername/Nier-Automata-editor/blob/a4a8d073c20e451734d6b499f9fec0a8d516876d/chips.py#L111) from:

    AVAILABLE_CHIPS = tuple(CHIPS_MAP.name_to_bytes_map.keys())

to this:

    AVAILABLE_CHIPS = tuple(sorted(CHIPS_MAP.name_to_bytes_map.keys()))

It works well. The chips are sorted by name in the drop down menu.

Please excuse me if this "fix" is bad in anyway. I have never really worked with Python.

**Comment by CensoredUsername** [comment]
Sorry for the slow response, should be fixed now.
