### ISSUE TITLE
chips editor is not working 

### ISSUE THREAD

**Issue by NzeroN** [CensoredUsername/Nier-Automata-editor#6]
i have tried to change some chip but when i saved and open chips editor again to check it nothing have happen , nothing have change

**Comment by CensoredUsername** [comment]
I couldn't reproduce this, so closing for now unless a better description of the problem can be given.

**Comment by matanui159** [comment]
I have the same issue with the editor. When I edit the chips, save, exit the program, enter again, the chips are reset back to what they were. Also to note: I have the NieR: Automata DLC installed
